# Generated by Django 5.1.7 on 2025-05-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_construct", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_construct.module",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_construct.questions",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_construct.module",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_construct.module",
            ),
        ),
        migrations.AddField(
            model_name="questions",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course_construct.test"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("module", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("title", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="test",
            unique_together={("module", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="questions",
            unique_together={("test", "question")},
        ),
    ]
