# Generated by Django 5.2 on 2025-05-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_construct", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="answers",
            name="answer",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
