# Generated by Django 5.2 on 2025-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_construct", "0004_alter_module_options_module_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
