# Generated by Django 5.2 on 2025-05-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_construct", "0005_alter_module_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["order"]},
        ),
        migrations.AlterUniqueTogether(
            name="questions",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="test",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="answers",
            name="answer",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="linkcontent",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="questions",
            name="question",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="test",
            name="title",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="questions",
            unique_together={("test", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("title", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="test",
            unique_together={("module", "title")},
        ),
    ]
