# Generated by Django 5.0 on 2025-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, upload_to="users_images/%Y/%m/%d"),
        ),
    ]
