# Generated by Django 5.1.7 on 2025-05-20 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_construct", "0002_initial"),
        ("courses", "0002_initial"),
        ("learn", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="favoritescourses",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="favoritescourses",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskfeedback",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskfeedback",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course_construct.task"
            ),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="task_feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learn.taskfeedback"
            ),
        ),
        migrations.AddField(
            model_name="testresults",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="testresults",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course_construct.test"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseprogress",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="favoritescourses",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="taskfeedback",
            unique_together={("student", "task")},
        ),
        migrations.AlterUniqueTogether(
            name="taskcomment",
            unique_together={("author", "task_feedback")},
        ),
        migrations.AlterUniqueTogether(
            name="testresults",
            unique_together={("student", "test")},
        ),
    ]
