# Generated by Django 5.0 on 2025-04-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, upload_to="course_images/%Y/%m/%d"),
        ),
    ]
