# Generated by Django 5.0 on 2025-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
