# Generated by Django 5.1.7 on 2025-04-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_author_id_courseprogress_favoritescourses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="author_id",
            new_name="author",
        ),
    ]
