# Generated by Django 5.1.7 on 2025-04-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_rename_author_id_course_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courseprogress",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="courseprogress",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="favoritescourses",
            old_name="course_id",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="favoritescourses",
            old_name="student_id",
            new_name="student",
        ),
    ]
